language: php
cache:
  directories:
  - vendor
php:
  - 5.6
  - 5.5
  - 5.4
  - nightly

matrix:
  allow_failures:
    - php: nightly
  
before_script:
  - alias composer="php -d zend.enable_gc=0 /usr/bin/composer"
  - composer require --dev satooshi/php-coveralls:dev-master
  - composer install
  
after_script:
  - export COVERALLS_RUN_LOCALLY=1
  - php bin/coveralls -v

script: 
  - bin/phpunit --coverage-text
  - bin/phpunit-randomizer --order rand

matrix:
     allow_failures:
         - php: hhvm-nightly  
branches:
  only:
    - master
 
