<?php
/**
 * Author: Nil Portugués Calderó <contact@nilportugues.com>
 * Date: 9/16/14
 * Time: 9:42 PM
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

return [
    //Generic
    'generic.is_required'                       => 'The :attribute field is required.',
    'generic.is_not_null'                       => 'The :attribute must be a non null value.',
    //Float
    'float'                                     => 'The :attribute must be a float.',
    'float.is_not_zero'                         => 'The :attribute must not be zero.',
    'float.is_positive'                         => 'The :attribute must be a positive value.',
    'float.is_positive_or_zero'                 => 'The :attribute must be a positive value or zero.',
    'float.is_negative'                         => 'The :attribute must be a negative value.',
    'float.is_negative_or_zero'                 => 'The :attribute must be a negative value or zero',
    'float.is_between'                          => 'The :attribute must be between :min and :max.',
    'float.is_odd'                              => 'The :attribute must be divisible by 3.',
    'float.is_even'                             => 'The :attribute must be divisible by 2.',
    'float.is_multiple'                         => 'The :attribute must be multiple of :size.',
    //Integer
    'integer'                                   => 'The :attribute must be an integer.',
    'integer.is_not_zero'                       => 'The :attribute must not be zero.',
    'integer.is_positive'                       => 'The :attribute must be a positive value.',
    'integer.is_positive_or_zero'               => 'The :attribute must be a positive value or zero.',
    'integer.is_negative'                       => 'The :attribute must be a negative value.',
    'integer.is_negative_or_zero'               => 'The :attribute must be a negative value or zero',
    'integer.is_between'                        => 'The :attribute must be between :min and :max.',
    'integer.is_odd'                            => 'The :attribute must be divisible by 3.',
    'integer.is_even'                           => 'The :attribute must be divisible by 2',
    'integer.is_multiple'                       => 'The :attribute must be multiple of :size.',
    //String
    'string'                                    => 'The :attribute must be a string.',
    'string.is_alphanumeric'                    => 'The :attribute may only contain letters and digits.',
    'string.is_alpha'                           => 'The :attribute may only contain letters.',
    'string.is_between'                         => 'The :attribute must be between :min and :max characters.',
    'string.is_charset'                         => 'The :attribute charset is not valid.',
    'string.is_all_consonants'                  => 'The :attribute may only have consonants.',
    'string.contains'                           => 'The :attribute was not found.',
    'string.is_control_characters'              => 'The :attribute may only have control characters.',
    'string.is_digit'                           => 'The :attribute must be :digits digits.',
    'string.ends_with'                          => 'The :attribute does not end with :string',
    'string.equals'                             => 'The :attribute and :other must match.',
    'string.in'                                 => 'The selected :attribute is invalid.',
    'string.has_graphical_chars_only'           => 'The :attribute may only have graphical characters.',
    'string.has_length'                         => 'The :attribute must be :size characters.',
    'string.is_lowercase'                       => 'The :attribute may only contain lower-cased letters.',
    'string.not_empty'                          => 'The :attribute is empty.',
    'string.no_whitespace'                      => 'The :attribute has white spaces.',
    'string.has_printable_chars_only'           => 'The :attribute may only have printable characters.',
    'string.is_punctuation'                     => 'The :attribute may only have punctuation symbols.',
    'string.matches_regex'                      => 'The :attribute format is invalid.',
    'string.is_slug'                            => 'The :attribute does not match :regex expression.',
    'string.is_space'                           => 'The :attribute is not a space.',
    'string.starts_with'                        => 'The :attribute does not start with :string',
    'string.is_uppercase'                       => 'The :attribute maybe only contain upper-cased letters.',
    'string.is_version'                         => 'The :attribute is not a valid version string.',
    'string.is_vowel'                           => 'The :attribute may only contain vowels.',
    'string.is_hex_digit'                       => 'The :attribute is not a valid hexadecimal value.',
    'string.has_lowercase'                      => 'The :attribute does not have at least :amount lower-cased characters.',
    'string.has_uppercase'                      => 'The :attribute does not have at least :amount upper-cased characters.',
    'string.has_numeric'                        => 'The :attribute does not have at least :amount numeric characters.',
    'string.has_special_characters'             => 'The :attribute does not have at least :amount special characters.',
    'string.is_email'                           => 'The :attribute must be a valid email address.',
    'string.is_url'                             => 'The :attribute must be a valid URL.',
    'string.is_uuid'                            => 'The :attribute must be a valid UUID.',
    //Object
    'object'                                    => 'The :attribute is not a valid object.',
    'object.is_instance_of'                     => 'The :attribute is not an instance of :object.',
    'object.has_property'                       => 'The :attribute property :property is not valid.',
    'object.has_method'                         => 'The :attribute method :method is not valid.',
    'object.has_parent_class'                   => 'The :attribute has no parent class :object.',
    'object.is_child_of'                        => 'The :attribute is not child of class :object.',
    'object.inherits_from'                      => 'The :attribute does not inherit from class :object.',
    'object.has_interface'                      => 'The :attribute does not implement interface :object.',
    //date_time
    'date_time'                                 => 'The :attribute is not a valid date.',
    'date_time.is_after'                        => 'The :attribute date must be a after :date.',
    'date_time.is_before'                       => 'The :attribute date must be a before :date.',
    'date_time.is_between'                      => 'The :attribute date must be between :min and :max.',
    'date_time.is_weekend'                      => 'The :attribute date is not a weekend day.',
    'date_time.is_weekday'                      => 'The :attribute date is not a weekday.',
    'date_time.is_monday'                       => 'The :attribute date is not Monday.',
    'date_time.is_tuesday'                      => 'The :attribute date is not Tuesday.',
    'date_time.is_wednesday'                    => 'The :attribute date is not Wednesday.',
    'date_time.is_thursday'                     => 'The :attribute date is not Thursday.',
    'date_time.is_friday'                       => 'The :attribute date is not Friday.',
    'date_time.is_saturday'                     => 'The :attribute date is not Saturday.',
    'date_time.is_sunday'                       => 'The :attribute date is not Sunday.',
    'date_time.is_today'                        => 'The :attribute date is not today.',
    'date_time.is_yesterday'                    => 'The :attribute date is not yesterday.',
    'date_time.is_tomorrow'                     => 'The :attribute date is not tomorrow.',
    'date_time.is_leap_year'                    => 'The :attribute must be a valid leap year.',
    'date_time.is_morning'                      => 'The :attribute is not morning.',
    'date_time.is_aftenoon'                     => 'The :attribute is not afternoon.',
    'date_time.is_evening'                      => 'The :attribute is not evening.',
    'date_time.is_night'                        => 'The :attribute is not night.',
    //Collection
    'collection'                                => 'The :attribute must be an array.',
    'collection.each'                           => '', //Will use the generated errors from the provided validators.
    'collection.has_key_format'                 => 'The :attribute array key format is not valid.',
    'collection.ends_with'                      => 'The :attribute array does not end as expected.',
    'collection.contains'                       => 'The :attribute was not found.',
    'collection.has_key'                        => 'The :attribute array has no :key.',
    'collection.has_length'                     => 'The :attribute must contain :size items.',
    'collection.is_not_empty'                   => 'The :attribute must have at least 1 item.',
    'collection.starts_with'                    => 'The :attribute array does not start as expected.',
    //FileUpload
    'file_upload'                               => 'The :attribute has no files.',
    'file_upload.is_between'                    => 'The :attribute must be between :min and :max :formatBytes.',
    'file_upload.is_mime_type'                  => 'The :attribute is not a valid file format.',
    'file_upload.has_file_name_format'          => 'The :attribute file name format is not valid.',
    'file_upload.has_valid_upload_directory'    => 'The :attribute upload directory is not valid.',
    'file_upload.not_overwriting_existing_file' => 'The :attribute upload will overwrite an existing file.',
    'file_upload.upload_err_ini_size'           => 'The :attribute upload exceeds the maximum file size allowed by the server.',
    'file_upload.upload_err_form_size'          => 'The :attribute upload exceeds the maximum file size specified in the form.',
    'file_upload.upload_err_partial'            => 'The :attribute was only partially uploaded.',
    'file_upload.upload_err_no_file'            => 'No :attribute file was uploaded.',
    'file_upload.upload_err_no_tmp_dir'         => 'Upload failed. Missing a temporary upload folder.',
    'file_upload.upload_err_cant_write'         => 'Upload failed. Failed to write file to disk.',
    'file_upload.upload_err_extension'          => 'Upload failed. File upload was stopped.',
    'file_upload.is_image'                      => 'The :attribute must be a valid image file.',
    'file_upload.has_length'                    => 'The :attribute must be :size files.'
];
